import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * 将多个局部 C/C++ 源文件合并为单个可独立编译的文件。
 * 默认输入顺序：keys_patterns.h, DFA.h, DFA.cpp, LexAnalysis.h。
 * 不会为合并文件添加 main，方便你后续自行补充。
 */
public class CppMerger {

	public static void main(String[] args) throws IOException {
		Path baseDir = Paths.get("").toAbsolutePath();
		List<String> inputs = Arrays.asList(
				"keys_patterns.h",
				"DFA.h",
				"DFA.cpp",
				"LexAnalysis.h"
		);

		Path output = args.length > 0
				? Paths.get(args[0])
				: baseDir.resolve("merged.cpp");

		Set<String> systemIncludes = new LinkedHashSet<>(); // 去重保持顺序
		StringBuilder body = new StringBuilder();

		for (String name : inputs) {
			Path file = baseDir.resolve(name);
			if (!Files.exists(file)) {
				throw new IOException("Missing input file: " + file);
			}

			List<String> lines = Files.readAllLines(file, StandardCharsets.UTF_8);

			body.append("// ---- BEGIN ").append(name).append(" ----\n");
			for (String line : lines) {
				String trimmed = line.trim();

				// 收集系统头文件，跳过本地头的 include
				if (trimmed.startsWith("#include")) {
					if (trimmed.contains("<")) {
						systemIncludes.add(trimmed);
					}
					continue;
				}

				// 跳过常见的头文件保护行
				if (trimmed.startsWith("#ifndef") || trimmed.startsWith("#define") || trimmed.startsWith("#endif")) {
					continue;
				}

				body.append(line).append('\n');
			}
			body.append("// ---- END ").append(name).append(" ----\n\n");
		}

		StringBuilder out = new StringBuilder();
		out.append("// Auto-generated by CppMerger. Inputs: ")
		   .append(String.join(", ", inputs))
		   .append("\n");

		for (String inc : systemIncludes) {
			out.append(inc).append('\n');
		}
		out.append('\n');
		out.append(body);

		Files.writeString(output, out.toString(), StandardCharsets.UTF_8,
				StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);

		System.out.println("Merged into: " + output.toAbsolutePath());
	}
}
