import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * 将多个局部 C/C++ 源文件合并为单个可独立编译的文件。
 * 默认输入顺序：keys_patterns.h, DFA.h, DFA.cpp, LexAnalysis.h。
 * 不会为合并文件添加 main，方便你后续自行补充。
 */
public class CppMerger {

	public static void main(String[] args) throws IOException {
		Path baseDir = Paths.get("").toAbsolutePath();
		List<String> inputs = Arrays.asList(
				"keys_patterns.h",
				"DFA.h",
				"DFA.cpp",
				"LexAnalysis.h"
		);

		Path output = args.length > 0
				? Paths.get(args[0])
				: baseDir.resolve("merged.cpp");

		Set<String> systemIncludes = new LinkedHashSet<>(); // 去重保持顺序
		StringBuilder body = new StringBuilder();

		for (String name : inputs) {
			Path file = baseDir.resolve(name);
			if (!Files.exists(file)) {
				throw new IOException("Missing input file: " + file);
			}

			List<String> lines = Files.readAllLines(file, StandardCharsets.UTF_8);

			body.append("/* ---- BEGIN ").append(name).append(" ---- */\n");

			String guardMacro = null; // track include guard to drop only that guard
			for (int idx = 0; idx < lines.size(); idx++) {
				String line = lines.get(idx);
				String trimmed = line.trim();

				// 收集系统头文件，跳过本地头的 include
				if (trimmed.startsWith("#include")) {
					if (trimmed.contains("<")) {
						systemIncludes.add(trimmed);
					}
					continue;
				}

				// 检测并跳过头文件保护（条件编译保留，只有 include guard 被去掉）
				if (guardMacro == null && trimmed.startsWith("#ifndef")) {
					String macro = trimmed.substring("#ifndef".length()).trim();
					int lookahead = idx + 1;
					while (lookahead < lines.size() && lines.get(lookahead).trim().isEmpty()) {
						lookahead++;
					}
					if (lookahead < lines.size()) {
						String nextTrim = lines.get(lookahead).trim();
						if (nextTrim.startsWith("#define")) {
							String macro2 = nextTrim.substring("#define".length()).trim();
							if (macro.equals(macro2) && !macro.isEmpty()) {
								guardMacro = macro;
								idx = lookahead; // skip both lines
								continue;
							}
						}
					}
				}

				if (guardMacro != null && trimmed.startsWith("#endif")) {
					guardMacro = null; // skip the matching endif of guard
					continue;
				}

				// 非 guard 的条件编译全部保留
				body.append(line).append('\n');
			}
			body.append("/* ---- END ").append(name).append(" ---- */\n\n");
		}

		StringBuilder out = new StringBuilder();
		out.append("// Auto-generated by CppMerger. Inputs: ")
		   .append(String.join(", ", inputs))
		   .append("\n");

		for (String inc : systemIncludes) {
			out.append(inc).append('\n');
		}
		out.append('\n');
		out.append(body);

		Files.writeString(output, out.toString(), StandardCharsets.UTF_8,
				StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);

		System.out.println("Merged into: " + output.toAbsolutePath());
	}
}
